- cg/src/domains/subjects/subjects.service.js
- cg/test/subjects/subjects.api.spec.js
> Adds proper error handing when an erased subjects data is requested

- .gitignore
- README.md
- cg/scripts/generate-config.js
- cg/scripts/generate_config.sh
- cg/scripts/get-wallet-pk.js
- quorum/README.md
Closes #38 
Testing instructions:
1. Stop your docker setup
1. Run: 
```
COMPOSE_PROJECT_NAME=clear-gdpr docker-compose down -v && \
docker volume rm $(docker volume ls -q) --force && \
docker network rm $(docker network ls -q)
```
2. Follow Quick Start Guide to create new `.env` files
3. Make sure there's `WALLET_PRIVATE_KEY` in `cg/.env`
4. Run the tests: `COMPOSE_PROJECT_NAME=clear-gdpr docker-compose exec cg yarn test`
> Added a script to generate WALLET_PRIVATE_KEY

- cg/src/domains/management/management.routes.js
- cg/src/domains/management/subjects/subjects.controller.js
- cg/src/domains/management/subjects/subjects.service.js
- cg/test/management/processors.api.spec.js
- cg/test/management/subjects.api.spec.js
Tests working isolated and in batch.
Closes #18 #33
> Management endpoint to list subjects and its tests, plus some cleanup

- .docs/.docs/cg/docs/CG_API.md
- CONTRIBUTION.md
- README.md
> fixed contributing links, and content

- frontend/src/containers/Login.js
- frontend/src/containers/SignUp.js
- frontend/src/elements/components/UserData.js
> Show data status by processor

- api/.env.example
- api/src/app.js
- cg/.env.example
- cg/src/app.js
> cors added

- admin-design/src/components/dashboard/GraphCard.js
- admin-design/src/pages/dashboard.css
Added some Victory Charts components and fixed the graphCard inner layout with css.
> Fix graphCard component layout and chart responsiveness

- docker-compose.yml
> Added a named volume for postgres service

- .travis.yml
- docker-compose.yml
> 0.0.5 release

- docker-compose.yml
- frontend/.env.example
- frontend/src/config.js
- setup.js
> Removed .env files for frontend

- cg/src/domains/subjects/subjects.service.js
- cg/test/management/processors.api.spec.js
- cg/test/management/stats.api.spec.js
- cg/test/management/subjects.api.spec.js
- cg/test/subjects/subjects.api.spec.js
Closes #93 
Quick fix for the processors having consent of erased subjects
> erase-data bug fix

- cg/src/domains/management/management.routes.js
- cg/src/domains/management/users/users.controller.js
- cg/src/domains/management/users/users.helpers.js
- cg/src/domains/management/users/users.service.js
- cg/test/management/users.api.spec.js
Postman and tests working, good for review
> Add endpoint to list managers and tests for it

- admin/package.json
- admin/src/components/Login/Login.js
- admin/src/components/core/cards/dashboard/Sidenav.js
- admin/src/containers/Login/Login.js
- admin/src/helpers/Session.js
- admin/src/helpers/routing/PrivateRoute.js
- admin/src/history.js
- admin/src/routes.js
- admin/yarn.lock
> Added private routes support and login + logout

- cg/.env.example
- cg/scripts/generate-config.js
- cg/src/utils/helpers.js
- cg/src/utils/jwt.js
- cg/test/subjects/subjects.api.spec.js
> added jwt token expiry and test

- admin/src/components/MainLayout/MainLayout.js
- admin/src/components/MainLayout/styles.css
- admin/src/components/Sidenav/Sidenav.js
- admin/src/components/core/cards/dashboard/Header.js
- admin/src/components/core/cards/dashboard/Panel.js
- admin/src/components/core/pages/Dashboard.js
- admin/src/containers/MainLayout/MainLayout.js
- admin/src/containers/Sidenav/Sidenav.js
- admin/src/routes.js
> Added main layout

- admin/.gitignore
- admin/config/jest/setupTests.js
- admin/package.json
- admin/src/components/Login/Login.test.js
- admin/src/components/Login/__snapshots__/Login.test.js.snap
- admin/yarn.lock
> Added basic test for Login component

- cg/src/domains/management/contract/contract.controller.js
- cg/src/domains/management/contract/contract.validators.js
- cg/src/domains/management/management.routes.js
- cg/src/domains/management/users/users.controller.js
- cg/src/domains/management/users/users.service.js
- cg/src/domains/management/users/users.validators.js
- cg/test/management/users.api.spec.js
Tested in Postman and using the Jest test suite, all working.
I left some questions in pieces of the code. Also waiting for more input about the snapshoting before a full update of the tests
Closes #146
> Add validators for management endpoints and small refactors in the tests

- admin/src/components/core/cards/dashboard/Form.js
- admin/src/components/core/cards/dashboard/TextInput.js
- admin/src/components/core/pages/Dashboard.js
- admin/src/components/core/pages/dashboard.css
Closes #127 
Added basic form elements and styling. Added Form and TextInput components.
> Feature/admin design/base form components

- api/.env.example
- cg/test/management/__snapshots__/contract.api.spec.js.snap
- cg/test/management/__snapshots__/processors.api.spec.js.snap
- cg/test/management/__snapshots__/subjects.api.spec.js.snap
- cg/test/management/__snapshots__/users.api.spec.js.snap
- cg/test/management/contract.api.spec.js
- cg/test/management/processors.api.spec.js
- cg/test/management/subjects.api.spec.js
- cg/test/management/users.api.spec.js
> Include snapshots in all tests and some refactor/cleanup

- cg/src/domains/management/subjects/subjects.controller.js
- cg/src/domains/management/subjects/subjects.service.js
- cg/test/management/subjects.api.spec.js
Postman and test suites working
Closes #164 #165
> Fix pagination issues

- admin/package.json
- admin/src/components/Login/Login.js
- admin/src/components/Login/Login.test.js
- admin/src/components/Login/__snapshots__/Login.test.js.snap
- admin/src/containers/Login/Login.js
- admin/src/containers/Login/Login.test.js
- admin/src/containers/Login/__snapshots__/Login.test.js.snap
- admin/src/helpers/routing/PrivateRoute.js
- admin/src/theme/Forms.css
- admin/src/theme/Login.css
- admin/yarn.lock
Close #142
Close #180
- Added support to forms with `react-forms`. This is a step forward to implement more reusable form components.
- Added loader when the form is submitted.
- Wrapped parent `handleLogin` into a promise to pass down to components.
- Added Errors wrapper, should be abstracted in Form Component (WIP) (#182)
- Some fixes to prop-types
> Login form improvements

- cg/src/domains/management/management.routes.js
- cg/src/domains/management/users/users.controller.js
- cg/src/domains/management/users/users.service.js
- cg/src/domains/management/users/users.validators.js
- cg/test/management/__snapshots__/users.api.spec.js.snap
- cg/test/management/users.api.spec.js
Closes #171 
Tests and Postman working.
> Remove managers endpoint

- admin/src/containers/MainLayout/MainLayout.js
> Added HOCs to wrap elements in context providers

- admin/src/components/core/cards/dashboard/ChartCard.js
- admin/src/components/core/cards/dashboard/GraphBar.js
- admin/src/components/core/cards/dashboard/GraphCard.js
- admin/src/components/core/cards/dashboard/Icon.js
- admin/src/components/core/cards/dashboard/ItemsCard.js
- admin/src/components/core/cards/dashboard/NumberCard.js
- admin/src/components/core/cards/dashboard/Overview.js
- admin/src/components/core/cards/dashboard/ProcessorCard.js
- admin/src/components/core/cards/dashboard/Processors.js
- admin/src/components/core/cards/dashboard/Sidenav.js
- admin/src/components/core/cards/dashboard/TableCard.js
Closes #141 
To remove warnings. Also, some proptypes could be standardized I will create a task for that.
> Added proptypes to kitchen sink

- .travis.yml
- admin/src/components/Processors/Processors.js
- admin/src/components/core/pages/Dashboard.js
- admin/src/containers/MainLayout/MainLayout.js
> Re-enabled warnings check on CI

- admin/src/components/Users/DeleteUser.js
- admin/src/components/Users/Users.js
- admin/src/components/core/cards/dashboard/Card.js
- admin/src/components/core/cards/dashboard/Sidenav.js
@Jakedavies that one's according to your comments + some free cleanup ;)
> Requiring handlers in props

- admin/src/components/Processors/EditProcessor.js
- admin/src/components/Processors/EditProcessor.test.js
- admin/src/components/Processors/__snapshots__/EditProcessor.test.js.snap
**Not ready to be merged**
Closes #204 
- Some concerns on Form testing should be addressed
- Processors Form for editing
> Processors form

- admin/src/containers/Processors/AddProcessor.js
- admin/src/containers/Processors/AddProcessor.test.js
- admin/src/containers/Processors/Processors.js
- admin/src/containers/Processors/__snapshots__/AddProcessor.test.js.snap
- admin/src/containers/Processors/__snapshots__/Processors.test.js.snap
> Processor Add 

- admin/src/components/Processors/DeleteProcessor.js
- admin/src/components/Processors/Processors.js
- admin/src/components/Processors/__snapshots__/Processors.test.js.snap
- admin/src/components/core/cards/dashboard/ProcessorCard.js
- admin/src/containers/Processors/DeleteProcessor.js
- admin/src/containers/Processors/DeleteProcessor.test.js
- admin/src/containers/Processors/Processors.js
- admin/src/containers/Processors/ProcessorsContext.js
- admin/src/containers/Processors/__snapshots__/DeleteProcessor.test.js.snap
- admin/src/containers/Processors/__snapshots__/Processors.test.js.snap
> Processor delete

- frontend/src/elements/components/UserData.js
> Renamed subject data status to keep consistency

- admin/src/components/Users/Users.js
- admin/src/containers/Rectifications/Rectifications.js
- admin/src/containers/Users/Users.js
> Added users prop-types

- cg/src/domains/management/subjects/subjects.service.js
- cg/src/domains/processors/processors.listeners.js
- cg/src/domains/subjects/subjects.service.js
- cg/src/utils/blockchain.js
- cg/test/management/__snapshots__/subjects.api.spec.js.snap
- cg/test/management/subjects.api.spec.js
- cg/test/processors/processors.listeners.spec.js
- cg/test/processors/start-all.spec.js
- cg/test/subjects/subjects.api.spec.js
Closes #178 
It's ready to receive reviews, works on Postman and all tests are passing!
> Add processor listeners for rectification events and a test for it

- cg/src/utils/encryption.js
- package.json
- yarn.lock
Updated findsecrets and ignored false-positive lines.
It's related to https://github.com/clevertech/DevOps/issues/10035
> Findsecrets update

- admin/src/components/Dashboard/Widgets/SubjectsList.js
- admin/src/components/Dashboard/Widgets/SubjectsList.test.js
- admin/src/components/Dashboard/Widgets/__snapshots__/SubjectsList.test.js.snap
- admin/src/components/Rectifications/Rectifications.js
- admin/src/components/Rectifications/__snapshots__/Rectifications.test.js.snap
- admin/src/components/Users/Users.js
- admin/src/components/Users/__snapshots__/Users.test.js.snap
- admin/src/components/core/Common/Table/Table.css
- admin/src/components/core/Common/Table/Table.js
- admin/src/components/core/cards/dashboard/Overview.js
- admin/src/components/core/cards/dashboard/TableCard.js
- admin/src/components/core/pages/dashboard.css
> Table component

- admin/src/components/Dashboard/Widgets/ConsentDial.js
- admin/src/components/Dashboard/Widgets/ConsentDial.test.js
- admin/src/components/Dashboard/Widgets/__snapshots__/ConsentDial.test.js.snap
- admin/src/components/Rectifications/Rectifications.test.js
- admin/src/components/Rectifications/__snapshots__/Rectifications.test.js.snap
- admin/src/components/core/cards/dashboard/GraphCard.js
- admin/src/components/core/cards/dashboard/Overview.js
- admin/src/containers/Rectifications/Rectifications.test.js
- admin/src/containers/Rectifications/__snapshots__/Rectifications.test.js.snap
I pushed in the informed refactor several fixes, but there were some pending on required props, is working now!
Also remove all the major warnings from the Kitchen Sink
> No more warnings on tests

- admin/src/components/Dashboard/Widgets/SubjectsList.js
- admin/src/containers/Rectifications/Details.js
- admin/src/containers/Rectifications/RectificationsContext.js
- admin/src/helpers/date-formatter.js
- admin/src/helpers/date-formatter.spec.js
> refactored to using a shared date-formatter function

- admin/package.json
Fixes issues with timezone difference in date formatting tests.
> Added timezone, so date formatting in tests is consistent

- admin/package.json
- api/package.json
- cg/package.json
- frontend/package.json
- package.json
- website/package-lock.json
- website/package.json
> Set version to 1.0.0 so we can rely on tags for releases

- api/README.md
- api/package.json
- api/test/app.spec.js
- api/test/utils.js
- cg/README.md
- cg/package.json
- cg/test/app.spec.js
- cg/test/utils.js
> removes "integration" test runner

- admin/src/containers/Processors/ProcessorsContext.js
Quick-fix of a bug I discovered during testing.
> Fixed deleting a processor in the UI

- frontend/config/jest/setupTests.js
- frontend/package.json
- frontend/yarn.lock
> Adding test support

- frontend/src/containers/App.js
> Hide 'sign in' and 'sign up' links from registered users

- admin/README.md
- api/scripts/generate-config.js
add default admin user credentials to the admin readme
add ALLOWED_REQUEST_ORIGIN setting to api env file generator
> Fix some things that causes difficulties during setup process

- frontend/src/containers/SignUp.js
> Sign up form - show error received from backend call

- admin/src/containers/Processors/AddProcessor.js
- admin/src/containers/Processors/AddProcessor.test.js
Fixes #
fix bug
add test to cover issue
None
closes #339
> fix bug preventing to add processor without scopes

- frontend/src/Elements/Element.js
- frontend/src/Elements/Elements.js
- frontend/src/Elements/components/Common/Button.js
- frontend/src/Elements/components/Common/Button.test.js
- frontend/src/Elements/components/Common/Checkbox.js
- frontend/src/Elements/components/Common/Checkbox.test.js
- frontend/src/Elements/components/Common/Switch.test.js
- frontend/src/Elements/components/Common/__snapshots__/Button.test.js.snap
- frontend/src/Elements/components/Common/__snapshots__/Checkbox.test.js.snap
- frontend/src/Elements/components/Common/__snapshots__/Switch.test.js.snap
- frontend/src/Elements/components/Consent/Consent.js
- frontend/src/Elements/components/Consent/Consent.test.js
- frontend/src/Elements/components/Consent/ConsentSuccess.test.js
- frontend/src/Elements/components/Consent/__snapshots__/Consent.test.js.snap
- frontend/src/Elements/components/Consent/__snapshots__/ConsentSuccess.test.js.snap
- frontend/src/Elements/components/Erasure/ForgottenRequest.js
- frontend/src/Elements/components/Erasure/ForgottenRequest.test.js
- frontend/src/Elements/components/Erasure/__snapshots__/ForgottenRequest.test.js.snap
- frontend/src/Elements/components/Portability/ExportRequest.js
- frontend/src/Elements/components/Portability/ExportRequest.test.js
- frontend/src/Elements/components/Portability/UserData.js
- frontend/src/Elements/components/Portability/UserData.test.js
- frontend/src/Elements/components/Portability/__snapshots__/ExportRequest.test.js.snap
- frontend/src/Elements/components/Portability/__snapshots__/UserData.test.js.snap
- frontend/src/Elements/components/Processors/Processor.js
- frontend/src/Elements/components/Processors/Processor.test.js
- frontend/src/Elements/components/Processors/ProcessorsList.test.js
- frontend/src/Elements/components/Processors/__snapshots__/Processor.test.js.snap
- frontend/src/js-sdk/cg.js
> Cover Elements SDK by tests

- cg/scripts/blockchain-function-test.js
- cg/scripts/deploy-blockchain-contract.js
- cg/src/app.js
- cg/src/domains/management/contract/contract.service.js
- cg/src/startup-routines.js
- cg/src/utils/blockchain/quorum-contract.js
Documenting the results of my research on deploying private smart contracts earlier this week.
This will be important in the future, let's put it it in the code already
> Initial results of the research in deploying private smart contracts

- frontend/src/Elements/Element.js
- frontend/src/Elements/components/Common/Switch.js
- frontend/src/Elements/components/Common/Switch.test.js
- frontend/src/Elements/components/Objection/Objection.js
- frontend/src/Elements/components/Objection/Objection.test.js
- frontend/src/Elements/components/Objection/__snapshots__/Objection.test.js.snap
- frontend/src/containers/Profile.js
- frontend/src/js-sdk/modules/subject.js
Add this element to demo page
Modify Switch element - add `disabled` state ssupport
Add new methods to JS SDK to support interaction with Objection
[Screenshot](http://pix.toile-libre.org/upload/original/1533726040.png)
closes #368
> Add new element to Element SDK - Objection

- frontend/package.json
- frontend/src/Elements/Element.js
- frontend/src/Elements/components/Rectification/Rectification.js
- frontend/src/Elements/components/Rectification/RectificationForm.js
- frontend/src/containers/Profile.js
- frontend/src/containers/SubjectContext.js
- frontend/src/js-sdk/modules/subject.js
- frontend/yarn.lock
I used json editor as we agreed to implement quick and dirty but working solution. Later we definitely need to provide better interface for Subjects to do changes in their personal data. Because of this, at this moment, I do not see any sense to cover new element by tests - it will be changed significantly and it is very likely that test will be rewritten completely. 
[screenshot](http://pix.toile-libre.org/upload/original/1533804454.png)
closes #284
> Implement Rectification element for Elements SDK

- admin/package.json
- admin/src/components/Dashboard/Widgets/Event.js
- admin/src/components/Dashboard/Widgets/EventsList.js
- admin/src/components/core/cards/dashboard/Card.js
- admin/src/components/core/cards/dashboard/TableCard.js
- admin/src/containers/Dashboard/Dashboard.js
- admin/src/containers/Dashboard/Widgets/EventsList.js
- admin/src/containers/Dashboard/Widgets/EventsList.test.js
- admin/src/containers/Dashboard/__snapshots__/Dashboard.test.js.snap
- admin/yarn.lock
> Create widget to display blockchain events in realtime

- cg/src/domains/subjects/subjects.service.js
- cg/test/subjects/subjects.api.spec.js
- frontend/src/Elements/Element.js
- frontend/src/Elements/components/Restriction/Restriction.js
- frontend/src/Elements/components/Restriction/Restriction.test.js
- frontend/src/Elements/components/Restriction/__snapshots__/Restriction.test.js.snap
- frontend/src/containers/Profile.js
- frontend/src/js-sdk/modules/subject.js
> Right to Rejection of processing

- api.md
Fixes #410 
- Added api.md (subject, management and processor).
- Use https://github.com/danielgtaylor/aglio to produce a html.
> Add API doc

- cg/src/domains/subjects/data-shares.service.js
- cg/src/domains/subjects/subjects.helpers.js
- cg/src/domains/subjects/subjects.service.js
> assert subject exist before any manipulation with subject data

- admin/src/components/Rectifications/Details.js
- admin/src/components/Rectifications/Details.test.js
- admin/src/components/Rectifications/__snapshots__/Details.test.js.snap
Fixes #413 
- Hide `Approve` button if request has been approved.
> Hide approve button when request is approved

- frontend/src/Elements/components/Portability/UserData.js
- frontend/src/Elements/components/Portability/__snapshots__/UserData.test.js.snap
- frontend/src/Elements/constants.js
- frontend/src/Elements/contexts/Subject.js
- frontend/src/Elements/theme/SubjectData.scss
- frontend/src/Elements/theme/_variables.scss
Fixes #337 
- Removed console.log
- Some styling to the current subject's data status
- Fixed issues on displaying new processors in subject's data status
> Subjects data status on new processor created

- cg/src/domains/subjects/subjects.helpers.js
- cg/src/domains/subjects/subjects.middlewares.js
- cg/src/domains/subjects/subjects.routes.js
- cg/src/domains/subjects/subjects.service.js
- cg/test/subjects/subjects.api.spec.js
Fixes #342 
- Added middleware `isSubjectErased` on `subject.routes`.
> Remove system access from erased subject

- README.md
Fixes #383 
- New main documentation including examples of integration of ClearGDPR, new repository structure and new introduction.
Note: Work in progress.
> Update documentation v2

- cg/test/subjects/subjects.api.spec.js
Fixes #
- URL endpoints were updated.
- Fix URL in subject test when blockchain fails in the process of giving consent.
> Fix subject test for blockchain

- lerna.json
- package.json
- yarn.lock
Closes #373 
Created the starter configuration. NPM packages will be placed inside `packages/` directory from now on.
Lerna allows to manage publishing, releasing and dependency in monorepos in a smoother way, with one command it detects what changed and publish it.
>  #373 Created starter lerna configuration

- packages/elements/src/Elements.js
> #370 Allow Elements SDK to be embedded single line 

- packages/js-sdk/src/modules/index.js
- packages/js-sdk/src/modules/processor.js
- packages/js-sdk/src/modules/processors.js
> add processor endpoints to js sdk

- packages/elements/DOCS.md
- packages/elements/REFERENCE.md
- packages/js-sdk/README.md
> Elements SDK Docs

- frontend/package.json
- frontend/yarn.lock
- website/package-lock.json
- website/package.json
- website/yarn.lock
Attempt to fix the security vulnerability mentioned by Michael
> yarn upgrade on the frontend and website dependencies

- admin/public/index.html
- admin/src/components/Dashboard/Widgets/EventsList.js
- admin/src/components/MainLayout/styles.css
- admin/src/components/Rectifications/Rectifications.js
- admin/src/components/Sidenav/Sidenav.js
- admin/src/components/core/Paginate.js
- admin/src/components/core/cards/dashboard/Card.js
- admin/src/containers/Dashboard/Dashboard.js
- admin/src/containers/Dashboard/__snapshots__/Dashboard.test.js.snap
- admin/src/containers/Users/UsersContext.js
- packages/js-sdk/package.json
> Admin Demo improvements

- admin/src/components/Dashboard/Widgets/EventsList.js
- admin/src/containers/Dashboard/Dashboard.js
- admin/src/containers/Dashboard/__snapshots__/Dashboard.test.js.snap
Hidden blockchain events panel for demo, since is not updating properly
> [hotfix] Blockchain events panel
